### ISSUE TITLE
Host docker部署：500 Internal Server Error: TypeError

### ISSUE THREAD

**Issue by Hanabi1688** [binjie09/duckduckgo-api#14]
按照docker部署的方法，部署后如图：
![image](https://github.com/binjie09/duckduckgo-api/assets/54924778/480c114a-e8e7-4998-baff-408d1e16083b)

公网访问报错500：
![image](https://github.com/binjie09/duckduckgo-api/assets/54924778/c79f2d35-0a47-4ebb-b782-cd13e85dae9f)

TypeError: The view function for 'hello_world' did not return a valid response. The function either returned None or ended without a return statement.
![image](https://github.com/binjie09/duckduckgo-api/assets/54924778/701692a3-eb65-4085-986c-3725b14d4b69)
请问要怎么解决，谢谢。

**Comment by LiberatorHg** [comment]
+1 老哥解决了吗

**Comment by Hanabi1688** [comment]
> +1 老哥解决了吗

还没有，看起来不太像是部署的问题，我也在等

**Comment by tejas36026** [comment]
same here bro.

**Comment by Ivesfsy** [comment]
r仍然是这个错误
内部服务器错误
服务器遇到内部错误，无法完成您的请求。服务器过载或应用程序中出现错误。

**Comment by Ivesfsy** [comment]
仍然是这个错误
内部服务器错误
服务器遇到内部错误，无法完成您的请求。服务器过载或应用程序中出现错误。
