### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by Chauban** [binjie09/duckduckgo-api#17]
部署后网页显示
404: NOT_FOUND
Code: NOT_FOUND
ID: sfo1::pvwz4-1709090754606-ecc43d39709e

请问是我步骤出错了吗

**Comment by Chenglukas** [comment]
vercel.json配置有问题

**Comment by Aichs** [comment]
> vercel.json配置有问题

那如何修改呢？

**Comment by SuiYunsy** [comment]
> > vercel.json配置有问题
> 
> 那如何修改呢？

可以看我的 [PR](https://github.com/binjie09/duckduckgo-api/pull/21)，已经解决了这个问题😀
