### ISSUE TITLE
https://duckduckgo-api.vercel.app/search這個API是官方的嗎？

### ISSUE THREAD

**Issue by 8337009** [binjie09/duckduckgo-api#3]
https://duckduckgo-api.vercel.app/search
這個API是官方的嗎？
為啥我沒有找到官方的API文檔，求指點

**Comment by binjie09** [comment]
不是官方的，是我部署的。现在用完了免费服务器用量，实际是模拟浏览器搜索duckduckgo然后提取网页内容格式化
