### ISSUE TITLE
返回null

### ISSUE THREAD

**Issue by zeraturing** [binjie09/duckduckgo-api#5]
如题，返回的信息是null

**Comment by binjie09** [comment]
目前发现是duckduckgo官方把这个库所用的接口删除了，等我有空了修复

**Comment by binjie09** [comment]
已修复，重新pip install -r requirements.txt即可

**Comment by zeraturing** [comment]
好的谢谢，我马上试一试

**Comment by zeraturing** [comment]
还是一样的报错，然后我加了一点调试信息，输出如下：
--------------------------------------------------
Keywords: 啊对对对是什么意思
Max results: 3
Results: None
Keywords: 啊对对对是什么意思
Max results: 3
Results: None

**Comment by zeraturing** [comment]
<img width="495" alt="image" src="https://github.com/binjie09/duckduckgo-api/assets/129106762/212bcd4f-e866-49cf-b28a-57c68887355e">
