### ISSUE TITLE
服务器部署请求报500

### ISSUE THREAD

**Issue by Numb94** [binjie09/duckduckgo-api#6]
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by hai-luo** [comment]
Same problem

**Comment by binjie09** [comment]
目前发现是duckduckgo官方把这个库所用的接口删除了，等我有空了修复

**Comment by binjie09** [comment]
> Same problem

已修复，重新pip install -r requirements.txt即可
